# Use Node 20 Alpine as base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package descriptors
COPY package.json package-lock.json ./

# Install npm packages
RUN npm install

# Copy source code files
COPY . .

# Expose Vite development server port
EXPOSE 3000

# Start Vite dev server in host mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
